name: Testing Context variables
on: 
  workflow_dispatch
env:
    cloud: google-cloud
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking context variable"
        run: |
          echo "Repository Name : S{{ github.repository }}"
          echo "workflow Nane : ${{ github.workflow }}"
          echo "Triggered by : ${{ github.triggering_actor }}"
