name: Testing workflow variables
on: 
  workflow_dispatch
env:
    cloud: google-cloud
jobs:
  greeting_fob:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Vishal
